import type { Fabric } from "./types";

export const fabrics: Fabric[] = [
  {
    id: "matte-nida",
    name: "Matte Nida",
    weight: "Medium",
    texture: "Dense, flat-woven synthetic weave with a soft, non-reflective face.",
    drape: "Falls in heavy, architectural folds; holds a clean silhouette without clinging.",
    recommendedOccasion: ["Everyday", "Work", "Travel"],
    care: "Cool machine wash, low iron, do not tumble dry.",
    motion: "subdued",
    accuracyTag: "representative",
  },
  {
    id: "silk-crepe",
    name: "Silk Crepe",
    weight: "Light",
    texture: "Fine pebbled surface with a dry, matte hand.",
    drape: "Soft, fluid movement that skims the body without full transparency.",
    recommendedOccasion: ["Work", "Evening", "Eid"],
    care: "Dry clean recommended; cold hand wash if tested for colourfastness.",
    motion: "slow-wave",
    accuracyTag: "representative",
  },
  {
    id: "satin",
    name: "Liquid Satin",
    weight: "Medium",
    texture: "Smooth, high-lustre face with a duller reverse.",
    drape: "Long, slow waves; bright specular highlights travel with movement.",
    recommendedOccasion: ["Evening", "Wedding"],
    care: "Dry clean only; store away from direct light to preserve sheen.",
    motion: "slow-wave",
    accuracyTag: "representative",
  },
  {
    id: "linen-blend",
    name: "Linen Blend",
    weight: "Light",
    texture: "Visible slubbed yarn, breathable, faintly irregular surface.",
    drape: "Crisp near the shoulder, softening through wear; creases are part of its character.",
    recommendedOccasion: ["Everyday", "Travel"],
    care: "Machine wash cold, line dry, iron while slightly damp.",
    motion: "still",
    accuracyTag: "representative",
  },
  {
    id: "jacquard",
    name: "Woven Jacquard",
    weight: "Medium",
    texture: "Pattern woven directly into the cloth; tonal relief rather than print.",
    drape: "Structured with gentle movement; surface detail shifts as light angle changes.",
    recommendedOccasion: ["Work", "Eid", "Wedding"],
    care: "Dry clean recommended to protect the raised weave.",
    motion: "structural",
    accuracyTag: "representative",
  },
  {
    id: "knitted-trim",
    name: "Knitted Trim",
    weight: "Medium",
    texture: "Fine-gauge knit used at cuff, collar and hem; visible thread structure.",
    drape: "Elasticated recovery at edges; adds definition where the garment meets the body.",
    recommendedOccasion: ["Everyday", "Work"],
    care: "Hand wash cold, dry flat to preserve shape.",
    motion: "still",
    accuracyTag: "representative",
  },
  {
    id: "lace",
    name: "Fine Lace",
    weight: "Light",
    texture: "Open, patterned needle-lace, typically layered over a lining.",
    drape: "Delicate and airy; moves independently of the base garment.",
    recommendedOccasion: ["Evening", "Wedding", "Eid"],
    care: "Dry clean only; handle raw edges with care.",
    motion: "high-frequency",
    accuracyTag: "representative",
  },
  {
    id: "chiffon-overlay",
    name: "Sheer Chiffon Overlay",
    weight: "Light",
    texture: "Sheer, plain-woven, faintly crisp hand that softens with wear.",
    drape: "Lightest movement in the collection; responsive to the smallest air current.",
    recommendedOccasion: ["Evening", "Wedding"],
    care: "Dry clean recommended; steam rather than press.",
    motion: "high-frequency",
    accuracyTag: "representative",
  },
  {
    id: "plain-unembroidered",
    name: "Plain Weave, Unembroidered",
    weight: "Medium",
    texture: "Even, smooth-faced weave with no applied surface detail.",
    drape: "Lets cut and proportion carry the design entirely.",
    recommendedOccasion: ["Everyday", "Work", "Travel"],
    care: "Machine wash cold, low iron.",
    motion: "still",
    accuracyTag: "representative",
  },
  {
    id: "hand-embroidered",
    name: "Hand-Threaded Embroidery",
    weight: "Medium",
    texture: "Base cloth carrying dense, hand-guided thread and bead work.",
    drape: "Weight concentrated at the embroidered field; the rest of the panel moves freely.",
    recommendedOccasion: ["Evening", "Wedding", "Eid"],
    care: "Dry clean only, by a cleaner experienced with embellished garments.",
    motion: "structural",
    accuracyTag: "representative",
  },
  {
    id: "fine-jewelry",
    name: "Rhodium-Plated Setting & Cubic Zirconia",
    weight: "Light",
    texture: "Polished metal band with a faceted centre stone and pavé halo.",
    drape: "N/A — structural setting, not a draped material.",
    recommendedOccasion: ["Evening", "Wedding", "Eid"],
    care: "Store in a soft pouch away from moisture and perfume; wipe with a dry microfibre cloth.",
    motion: "still",
    accuracyTag: "representative",
  },
];

export function getFabric(id: string) {
  return fabrics.find((f) => f.id === id);
}
