import type { MaterialVariant, Product, ProductImage } from "./types";

function img(seed: string, alt: string, aspect: ProductImage["aspect"] = "portrait"): ProductImage {
  return { src: seed, alt, aspect };
}

function variant(id: string, label: string, colorHex: string, fabricId: MaterialVariant["fabricId"]): MaterialVariant {
  return { id, label, colorHex, fabricId };
}

const SIZES = ["XS", "S", "M", "L", "XL", "XXL"];
const LENGTHS = ['Petite (54")', 'Standard (56")', 'Tall (58")'];
const CARE_STANDARD = ["Dry clean recommended", "Store on a padded hanger", "Steam rather than press over embroidery"];

export const products: Product[] = [
  {
    id: "p-dalia-architectural",
    slug: "dalia-architectural-abaya",
    name: "Dalia Architectural Abaya",
    nameArabic: "داليا",
    collectionSlug: "the-obsidian-edit",
    description:
      "A straight-cut abaya built entirely from a single considered seam line. No embroidery, no trim — the silhouette is the design.",
    editorialDescription:
      "A fluid, unembroidered silhouette defined by a restrained shoulder line and a single tonal seam that runs the full length of the front edge. Black is treated here as a study in construction rather than a backdrop for decoration.",
    price: 1450,
    currency: "AED",
    colours: [
      variant("obsidian", "Obsidian", "#0d0d0d", "plain-unembroidered"),
      variant("ink", "Ink", "#151515", "plain-unembroidered"),
    ],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday", "Work"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("dalia-front", "Dalia Architectural Abaya, front view, obsidian", "portrait"),
      img("dalia-back", "Dalia Architectural Abaya, back view showing seam line", "portrait"),
      img("dalia-detail", "Detail of the front seam construction", "detail"),
    ],
    isFeatured: true,
    relatedProductIds: ["p-safa-structured-nida", "p-mira-tonal-jacquard"],
    modelMeasurements: 'Model is 175cm / 5\'9", wearing size S, Standard length.',
    productMeasurements: 'Size M: bust 118cm, length 142cm, sleeve 58cm.',
    constructionDetails: [
      "Single-panel front seam, top-stitched in tonal thread",
      "Set-in sleeve with a clean underarm gusset",
      "Weighted hem for a controlled fall",
    ],
    accuracyTag: "conceptual",
  },
  {
    id: "p-safa-structured-nida",
    slug: "safa-structured-nida",
    name: "Safa Structured Nida",
    collectionSlug: "the-obsidian-edit",
    description: "An A-line Nida abaya with a structured shoulder and tonal topstitching along the front placket.",
    editorialDescription:
      "Matte Nida holds its shape through a structured shoulder and a controlled A-line body. Tonal topstitching along the front placket catches light only when the wearer moves.",
    price: 1290,
    currency: "AED",
    colours: [
      variant("obsidian", "Obsidian", "#0d0d0d", "matte-nida"),
      variant("stone", "Stone", "#6e6963", "matte-nida"),
    ],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "A-line",
    sleeve: "Straight",
    occasion: ["Everyday", "Work", "Travel"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("safa-front", "Safa Structured Nida, front view", "portrait"),
      img("safa-back", "Safa Structured Nida, back view", "portrait"),
      img("safa-detail", "Detail of tonal topstitching at the front placket", "detail"),
    ],
    isNew: true,
    relatedProductIds: ["p-dalia-architectural", "p-reem-tailored"],
    modelMeasurements: 'Model is 173cm / 5\'8", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 120cm, length 140cm, sleeve 57cm.",
    constructionDetails: ["Structured shoulder yoke", "A-line body with side seam shaping", "Tonal topstitched placket"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-mira-tonal-jacquard",
    slug: "mira-tonal-jacquard",
    name: "Mira Tonal Jacquard",
    collectionSlug: "the-obsidian-edit",
    description: "Woven jacquard in tonal black, where a geometric pattern is set into the cloth rather than printed.",
    editorialDescription:
      "A restrained geometric pattern is woven directly into black jacquard, visible only as a shift in surface texture as light moves across it — no print, no contrast thread.",
    price: 1690,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "jacquard")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "jacquard",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Work", "Eid"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "made-to-order",
    images: [
      img("mira-front", "Mira Tonal Jacquard, front view", "portrait"),
      img("mira-detail", "Close-up of the woven geometric jacquard pattern", "detail"),
      img("mira-back", "Mira Tonal Jacquard, back view", "portrait"),
    ],
    relatedProductIds: ["p-dalia-architectural", "p-safa-structured-nida"],
    modelMeasurements: 'Model is 176cm / 5\'9", wearing size M, Standard length.',
    productMeasurements: "Size M: bust 122cm, length 141cm, sleeve 58cm.",
    constructionDetails: ["Jacquard-woven tonal pattern", "Straight cut with side vents", "Hand-finished hem"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-layali-crystal",
    slug: "layali-crystal-abaya",
    name: "Layali Crystal Abaya",
    nameArabic: "ليالي",
    collectionSlug: "evening-light",
    description: "A satin evening abaya with hand-set crystal along the front edge and cuff.",
    editorialDescription:
      "Liquid satin falls in long, slow waves, catching light across hand-set crystal placed along the open front edge and cuff — a quiet reflective line rather than an all-over sparkle.",
    price: 3200,
    compareAtPrice: 3650,
    currency: "AED",
    colours: [
      variant("obsidian", "Obsidian", "#0d0d0d", "satin"),
      variant("burgundy", "Deep Burgundy", "#4a1420", "satin"),
    ],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "satin",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Evening", "Wedding"],
    embroideryType: "None",
    embellishmentType: "Hand-set crystal",
    care: ["Dry clean only", "Store flat or on a padded hanger", "Keep away from direct light"],
    availability: "limited",
    images: [
      img("layali-front", "Layali Crystal Abaya, front view, burgundy satin", "portrait"),
      img("layali-detail", "Detail of hand-set crystal along the front edge", "detail"),
      img("layali-back", "Layali Crystal Abaya, back view", "portrait"),
    ],
    isLimited: true,
    isFeatured: true,
    relatedProductIds: ["p-lujain-evening", "p-hala-satin-trim"],
    modelMeasurements: 'Model is 174cm / 5\'8", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 119cm, length 143cm, sleeve 58cm.",
    constructionDetails: [
      "Hand-set crystal, applied after garment construction",
      "Fully lined bodice for structure",
      "Weighted hem for a clean line while seated",
    ],
    accuracyTag: "conceptual",
  },
  {
    id: "p-lujain-evening",
    slug: "lujain-evening-abaya",
    name: "Lujain Evening Abaya",
    collectionSlug: "evening-light",
    description: "A butterfly-cut silk crepe abaya designed to move with the wearer under low light.",
    editorialDescription:
      "Silk crepe in a butterfly cut opens into soft volume at the arm, closing to a fitted line at the wrist — designed for rooms lit by candle and low warm light rather than daylight.",
    price: 2450,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "silk-crepe"), variant("burgundy", "Deep Burgundy", "#4a1420", "silk-crepe")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "silk-crepe",
    cut: "Butterfly",
    sleeve: "Bell",
    occasion: ["Evening", "Eid"],
    embroideryType: "None",
    embellishmentType: "None",
    care: ["Dry clean recommended", "Cold hand wash only if colourfastness has been tested"],
    availability: "in-stock",
    images: [
      img("lujain-front", "Lujain Evening Abaya, front view", "portrait"),
      img("lujain-motion", "Lujain Evening Abaya captured mid-movement", "landscape"),
      img("lujain-detail", "Detail of the bell sleeve opening", "detail"),
    ],
    relatedProductIds: ["p-layali-crystal", "p-ayla-layered-chiffon"],
    modelMeasurements: 'Model is 175cm / 5\'9", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 121cm, length 142cm, sleeve 60cm.",
    constructionDetails: ["Butterfly cut with underarm gusset", "Bell sleeve with fitted wrist band", "Silk crepe underlayer"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-hala-satin-trim",
    slug: "hala-satin-trim-abaya",
    name: "Hala Satin-Trim Abaya",
    isFeatured: true,
    collectionSlug: "evening-light",
    description: "An A-line abaya with fine metallic thread following the open front and cuff against matte black crepe.",
    editorialDescription:
      "Fine metallic thread follows the open front and cuff, creating a quiet reflective detail against matte black crepe — a single considered line rather than an embellished surface.",
    price: 2150,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "silk-crepe")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "silk-crepe",
    cut: "A-line",
    sleeve: "Cuffed",
    occasion: ["Evening", "Eid"],
    embroideryType: "Metallic thread outline",
    embellishmentType: "Metallic thread",
    care: ["Dry clean only", "Steam rather than press over metallic thread"],
    availability: "in-stock",
    images: [
      img("hala-front", "Hala Satin-Trim Abaya, front view", "portrait"),
      img("hala-detail", "Detail of metallic thread along the front edge", "detail"),
      img("hala-back", "Hala Satin-Trim Abaya, back view", "portrait"),
    ],
    relatedProductIds: ["p-layali-crystal", "p-lujain-evening"],
    modelMeasurements: 'Model is 172cm / 5\'8", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 119cm, length 141cm, sleeve 57cm.",
    constructionDetails: ["Metallic thread couched by hand along front edge", "Cuffed sleeve with concealed button", "A-line body"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-ayla-layered-chiffon",
    slug: "ayla-layered-chiffon",
    name: "Ayla Layered Chiffon",
    collectionSlug: "evening-light",
    description: "A sheer chiffon overlay layered over a fully-lined satin base, moving independently of the body.",
    editorialDescription:
      "A sheer chiffon layer floats over a fully-lined satin base, responding to the smallest current of air — the lightest movement in the collection, built for evenings that ask for drama without weight.",
    price: 2890,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "chiffon-overlay")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "chiffon-overlay",
    cut: "Layered",
    sleeve: "Flared",
    occasion: ["Evening", "Wedding"],
    embroideryType: "None",
    embellishmentType: "None",
    care: ["Dry clean recommended", "Steam only, do not press the chiffon layer"],
    availability: "in-stock",
    images: [
      img("ayla-front", "Ayla Layered Chiffon, front view", "portrait"),
      img("ayla-motion", "Ayla Layered Chiffon overlay in motion", "landscape"),
      img("ayla-detail", "Detail where the chiffon overlay meets the satin base", "detail"),
    ],
    isNew: true,
    relatedProductIds: ["p-lujain-evening", "p-layali-crystal"],
    modelMeasurements: 'Model is 174cm / 5\'9", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 120cm, length 143cm, sleeve 59cm.",
    constructionDetails: ["Independent chiffon overlay panel", "Fully-lined satin base", "Flared sleeve, double layer"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-noor-pleated",
    slug: "noor-pleated-abaya",
    name: "Noor Pleated Abaya",
    nameArabic: "نور",
    collectionSlug: "quiet-structure",
    description: "A workwear abaya in linen blend with a controlled box pleat set at the back yoke.",
    editorialDescription:
      "A set shoulder and a single controlled box pleat at the back yoke give this linen-blend piece room to move through a long working day, without surrendering its clean front line.",
    price: 1580,
    currency: "AED",
    colours: [variant("stone", "Stone", "#6e6963", "linen-blend"), variant("sand", "Desert Sand", "#d4c5b9", "linen-blend")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "linen-blend",
    cut: "Pleated",
    sleeve: "Straight",
    occasion: ["Work", "Everyday"],
    embroideryType: "None",
    embellishmentType: "None",
    care: ["Machine wash cold", "Line dry", "Iron while slightly damp"],
    availability: "in-stock",
    images: [
      img("noor-front", "Noor Pleated Abaya, front view, stone", "portrait"),
      img("noor-back", "Noor Pleated Abaya, back view showing box pleat", "portrait"),
      img("noor-detail", "Detail of the back yoke box pleat", "detail"),
    ],
    isFeatured: true,
    relatedProductIds: ["p-reem-tailored", "p-widad-box-pleat"],
    modelMeasurements: 'Model is 173cm / 5\'8", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 120cm, length 140cm, sleeve 58cm.",
    constructionDetails: ["Set-in shoulder yoke", "Single box pleat at centre back", "Reinforced underarm for daily wear"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-reem-tailored",
    slug: "reem-tailored-abaya",
    name: "Reem Tailored Abaya",
    collectionSlug: "quiet-structure",
    description: "A tailored straight-cut Nida abaya with a clean set shoulder, built for daily wear.",
    editorialDescription:
      "A tailored set shoulder and a straight body cut from matte Nida chosen specifically for its recovery — this is a piece designed to hold its shape through an eight-hour day, not just a first impression.",
    price: 1390,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "matte-nida"), variant("stone", "Stone", "#6e6963", "matte-nida")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Work", "Everyday"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("reem-front", "Reem Tailored Abaya, front view", "portrait"),
      img("reem-back", "Reem Tailored Abaya, back view", "portrait"),
      img("reem-detail", "Detail of the tailored shoulder seam", "detail"),
    ],
    relatedProductIds: ["p-noor-pleated", "p-safa-structured-nida"],
    modelMeasurements: 'Model is 175cm / 5\'9", wearing size M, Standard length.',
    productMeasurements: "Size M: bust 122cm, length 141cm, sleeve 58cm.",
    constructionDetails: ["Tailored set shoulder", "Straight body, side vents", "Reinforced daily-wear seaming"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-widad-box-pleat",
    slug: "widad-box-pleat-abaya",
    name: "Widad Box-Pleat Abaya",
    collectionSlug: "quiet-structure",
    description: "A pleated Nida abaya with movement built into the skirt through a series of fine box pleats.",
    editorialDescription:
      "A series of fine box pleats, set from the natural waistline down, give this Nida piece controlled movement without added volume at the shoulder.",
    price: 1620,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "matte-nida")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "Pleated",
    sleeve: "Straight",
    occasion: ["Work", "Everyday"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("widad-front", "Widad Box-Pleat Abaya, front view", "portrait"),
      img("widad-detail", "Detail of the fine box pleats at the skirt", "detail"),
      img("widad-back", "Widad Box-Pleat Abaya, back view", "portrait"),
    ],
    relatedProductIds: ["p-noor-pleated", "p-reem-tailored"],
    modelMeasurements: 'Model is 174cm / 5\'8", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 121cm, length 142cm, sleeve 58cm.",
    constructionDetails: ["Fine box pleats from natural waist", "Set-in straight sleeve", "Clean unadorned shoulder"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-rawan-embroidered-bisht",
    slug: "rawan-embroidered-bisht",
    name: "Rawan Embroidered Bisht",
    nameArabic: "روان",
    collectionSlug: "the-embroidered-atelier",
    description: "A bisht-silhouette overlay abaya with hand-guided threadwork along the front edge and shoulder.",
    editorialDescription:
      "A bisht-inspired open overlay carries hand-guided threadwork along the shoulder and front edge, each line set by a single embroiderer from start to finish — thread density varies slightly piece to piece by design.",
    price: 3850,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Wedding", "Eid", "Evening"],
    embroideryType: "Hand-guided thread, shoulder and front edge",
    embellishmentType: "Metallic thread",
    care: ["Dry clean only, by a cleaner experienced with embellished garments"],
    availability: "made-to-order",
    images: [
      img("rawan-front", "Rawan Embroidered Bisht, front view", "portrait"),
      img("rawan-detail", "Close-up of hand-guided thread embroidery at the shoulder", "detail"),
      img("rawan-back", "Rawan Embroidered Bisht, back view", "portrait"),
    ],
    isFeatured: true,
    isLimited: true,
    relatedProductIds: ["p-samira-pearl-cuff", "p-yara-hand-threaded"],
    modelMeasurements: 'Model is 175cm / 5\'9", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 124cm, length 143cm, sleeve 60cm.",
    constructionDetails: [
      "Overlay bisht panel, open front",
      "Hand-guided metallic thread embroidery",
      "Fully lined base garment",
    ],
    accuracyTag: "conceptual",
  },
  {
    id: "p-samira-pearl-cuff",
    slug: "samira-pearl-cuff-abaya",
    name: "Samira Pearl-Cuff Abaya",
    collectionSlug: "the-embroidered-atelier",
    description: "A straight-cut abaya with hand-set pearl beading concentrated at the cuff.",
    editorialDescription:
      "Weight is concentrated deliberately at the cuff, where hand-set pearl beading sits densest — the rest of the panel is left plain, so the detail reads as considered rather than continuous.",
    price: 2650,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "hand-embroidered"), variant("ivory", "Warm Ivory", "#f4f0e9", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Straight",
    sleeve: "Cuffed",
    occasion: ["Evening", "Eid"],
    embroideryType: "None",
    embellishmentType: "Hand-set pearl beading",
    care: ["Dry clean only, by a cleaner experienced with embellished garments"],
    availability: "in-stock",
    images: [
      img("samira-front", "Samira Pearl-Cuff Abaya, front view", "portrait"),
      img("samira-detail", "Detail of hand-set pearl beading at the cuff", "detail"),
      img("samira-back", "Samira Pearl-Cuff Abaya, back view", "portrait"),
    ],
    isNew: true,
    relatedProductIds: ["p-rawan-embroidered-bisht", "p-yara-hand-threaded"],
    modelMeasurements: 'Model is 173cm / 5\'8", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 120cm, length 141cm, sleeve 58cm.",
    constructionDetails: ["Hand-set pearl beading, cuff only", "Straight cut, plain body", "Concealed cuff closure"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-yara-hand-threaded",
    slug: "yara-hand-threaded-abaya",
    name: "Yara Hand-Threaded Abaya",
    collectionSlug: "the-embroidered-atelier",
    description: "An open-front abaya with a full hand-threaded composition along the front panel.",
    editorialDescription:
      "The most involved piece in the atelier: a full hand-threaded composition runs the length of the front panel, built up over multiple sessions by a single embroiderer.",
    price: 4650,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Wedding", "Eid"],
    embroideryType: "Full front composition, hand-threaded",
    embellishmentType: "Metallic thread, crystal",
    care: ["Dry clean only, by a cleaner experienced with embellished garments"],
    availability: "made-to-order",
    images: [
      img("yara-front", "Yara Hand-Threaded Abaya, front view", "portrait"),
      img("yara-detail", "Close-up of the full front hand-threaded composition", "detail"),
      img("yara-back", "Yara Hand-Threaded Abaya, back view", "portrait"),
    ],
    isLimited: true,
    relatedProductIds: ["p-rawan-embroidered-bisht", "p-samira-pearl-cuff"],
    modelMeasurements: 'Model is 174cm / 5\'9", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 123cm, length 143cm, sleeve 60cm.",
    constructionDetails: [
      "Full front hand-threaded composition",
      "Open front, layered sleeve",
      "Multiple embroidery sessions per garment",
    ],
    accuracyTag: "conceptual",
  },
  {
    id: "p-amal-essential-nida",
    slug: "amal-essential-nida",
    name: "Amal Essential Nida",
    nameArabic: "أمل",
    collectionSlug: "essential-nida",
    description: "The foundational straight-cut Nida abaya — no embroidery, refined proportion only.",
    editorialDescription:
      "No embroidery, no embellishment: proportion refined over several seasons is the entire design. This is the piece the rest of the collection is measured against.",
    price: 990,
    currency: "AED",
    colours: [
      variant("obsidian", "Obsidian", "#0d0d0d", "matte-nida"),
      variant("stone", "Stone", "#6e6963", "matte-nida"),
      variant("sand", "Desert Sand", "#d4c5b9", "matte-nida"),
    ],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday", "Travel"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("amal-front", "Amal Essential Nida, front view", "portrait"),
      img("amal-back", "Amal Essential Nida, back view", "portrait"),
      img("amal-detail", "Detail of the plain Nida weave", "detail"),
    ],
    isFeatured: true,
    relatedProductIds: ["p-latifa-minimal-nida", "p-hind-everyday-nida"],
    modelMeasurements: 'Model is 172cm / 5\'8", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 118cm, length 140cm, sleeve 57cm.",
    constructionDetails: ["Single-panel front", "Straight set sleeve", "Refined proportion, no applied detail"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-latifa-minimal-nida",
    slug: "latifa-minimal-nida",
    name: "Latifa Minimal Nida",
    collectionSlug: "essential-nida",
    description: "An A-line Nida abaya with a slightly fuller body, still without embellishment.",
    editorialDescription:
      "An A-line variation of the essential line, cut with a slightly fuller body for those who prefer more room through the hip and hem, while keeping the collection's plain, unembroidered face.",
    price: 1050,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "matte-nida"), variant("clay", "Soft Clay", "#9e8e80", "matte-nida")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "A-line",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("latifa-front", "Latifa Minimal Nida, front view", "portrait"),
      img("latifa-back", "Latifa Minimal Nida, back view", "portrait"),
      img("latifa-detail", "Detail of the A-line hem", "detail"),
    ],
    relatedProductIds: ["p-amal-essential-nida", "p-hind-everyday-nida"],
    modelMeasurements: 'Model is 173cm / 5\'8", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 122cm, length 141cm, sleeve 57cm.",
    constructionDetails: ["A-line body", "Straight set sleeve", "Plain unembroidered face"],
    accuracyTag: "conceptual",
  },
  {
    id: "p-hind-everyday-nida",
    slug: "hind-everyday-nida",
    name: "Hind Everyday Nida",
    collectionSlug: "essential-nida",
    description: "A butterfly-cut Nida abaya designed for ease of movement through the day.",
    editorialDescription:
      "A butterfly cut opens gently at the arm for ease of movement, cut from the same matte Nida as the rest of the essential line, with no applied embellishment.",
    price: 1120,
    currency: "AED",
    colours: [variant("obsidian", "Obsidian", "#0d0d0d", "matte-nida"), variant("stone", "Stone", "#6e6963", "matte-nida")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "Butterfly",
    sleeve: "Straight",
    occasion: ["Everyday", "Travel"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("hind-front", "Hind Everyday Nida, front view", "portrait"),
      img("hind-back", "Hind Everyday Nida, back view", "portrait"),
      img("hind-detail", "Detail of the butterfly cut underarm", "detail"),
    ],
    isNew: true,
    relatedProductIds: ["p-amal-essential-nida", "p-latifa-minimal-nida"],
    modelMeasurements: 'Model is 174cm / 5\'9", wearing size S, Standard length.',
    productMeasurements: "Size M: bust 121cm, length 141cm, sleeve 59cm.",
    constructionDetails: ["Butterfly cut with underarm gusset", "Straight hem", "Plain unembroidered face"],
    accuracyTag: "conceptual",
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCollection(collectionSlug: string) {
  return products.filter((p) => p.collectionSlug === collectionSlug);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.isFeatured);
}

export function getRelatedProducts(product: Product) {
  return product.relatedProductIds
    .map((id) => products.find((p) => p.id === id))
    .filter((p): p is Product => Boolean(p));
}
