import type { MaterialVariant, Product, ProductImage } from "./types";

// Source: Zoya Fashion & Abaya Hub WhatsApp Business catalog (wa.me/c/971564731247),
// pulled 2026-08-05. Name, price and description text below are taken directly from
// the live catalog. Structural fields not exposed by the catalog (cut/sleeve taxonomy,
// colour hex, sizes, lengths, measurements, construction notes) are reasonable defaults
// pending real spec sheets from the supplier — hence accuracyTag: "representative"
// throughout. Photography is still the procedural placeholder (see public/models/README.md)
// until real product photos are sourced and dropped into public/images/.

function img(seed: string, alt: string, aspect: ProductImage["aspect"] = "portrait"): ProductImage {
  return { src: seed, alt, aspect };
}

function variant(id: string, label: string, colorHex: string, fabricId: MaterialVariant["fabricId"]): MaterialVariant {
  return { id, label, colorHex, fabricId };
}

const SIZES = ["S", "M", "L", "XL", "XXL"];
const LENGTHS = ['Standard (56")', 'Tall (58")'];
const CARE_STANDARD = ["Dry clean recommended", "Store on a padded hanger", "Steam rather than press over embroidery"];

export const products: Product[] = [
  // ---------- Signature Abayas ----------
  {
    id: "p-black-floral-pink",
    slug: "black-floral-embroidered-abaya-pink",
    name: "Black Floral Embroidered Abaya",
    collectionSlug: "signature-abayas",
    description: "Black front-open abaya with delicate pink floral embroidery along the front panel and sleeves.",
    editorialDescription:
      "Elegant black front-open abaya adorned with delicate pink floral embroidery along the front panel and sleeves. Crafted from soft, flowy fabric with a graceful silhouette, it offers timeless style and all-day comfort — perfect for everyday wear, gatherings, and special occasions.",
    price: 120,
    currency: "AED",
    colours: [variant("black-pink", "Black / Pink Embroidery", "#0d0d0d", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Front-open",
    sleeve: "Straight",
    occasion: ["Everyday", "Eid"],
    embroideryType: "Pink floral embroidery, front panel and sleeves",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("/images/products/black-floral-pink-front/1.jpeg", "Black Floral Embroidered Abaya, pink embroidery, front view", "portrait"),
      img("/images/products/black-floral-pink-front/2.jpeg", "Black Floral Embroidered Abaya, pink embroidery, detail view", "portrait"),
      img("/images/products/black-floral-pink-front/3.jpeg", "Black Floral Embroidered Abaya, pink embroidery, detail view", "portrait"),
      img("/images/products/black-floral-pink-front/4.jpeg", "Black Floral Embroidered Abaya, pink embroidery, detail view", "portrait"),
    ],
    videos: ["/images/products/black-floral-pink-front/v1.mp4"],
    isFeatured: true,
    relatedProductIds: ["p-black-floral-red", "p-premium-floral-embellished"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open silhouette", "Soft, flowy fabric", "Graceful, relaxed drape"],
    accuracyTag: "representative",
  },
  {
    id: "p-premium-floral-embellished",
    slug: "premium-floral-embellished-abaya",
    name: "Premium Floral Embellished Abaya",
    collectionSlug: "signature-abayas",
    description: "Premium black abaya with 3D floral embellishments and delicate beadwork, includes matching scarf.",
    editorialDescription:
      "Grace your look with this premium black abaya featuring beautiful 3D floral embellishments and delicate beadwork. Soft, elegant, and perfect for special occasions. Includes matching black scarf.",
    price: 120,
    currency: "AED",
    colours: [variant("black", "Black", "#0d0d0d", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Front-open",
    sleeve: "Straight",
    occasion: ["Evening", "Eid", "Wedding"],
    embroideryType: "None",
    embellishmentType: "3D floral embellishment and beadwork",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("/images/products/premium-floral-embellished-front/1.jpeg", "Premium Floral Embellished Abaya, front view", "portrait"),
      img("/images/products/premium-floral-embellished-front/2.jpeg", "Premium Floral Embellished Abaya, detail view", "portrait"),
      img("/images/products/premium-floral-embellished-front/3.jpeg", "Premium Floral Embellished Abaya, detail view", "portrait"),
    ],
    videos: ["/images/products/premium-floral-embellished-front/v1.mp4"],
    isFeatured: true,
    relatedProductIds: ["p-black-floral-pink", "p-blush-pink-embellished"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open silhouette", "3D floral embellishment", "Includes matching scarf"],
    accuracyTag: "representative",
  },
  {
    id: "p-white-crystal-work",
    slug: "white-crystal-work-abaya",
    name: "White Crystal Work Abaya",
    collectionSlug: "signature-abayas",
    description: "Grey abaya with delicate white crystal work, includes matching white scarf.",
    editorialDescription:
      "Elegant grey abaya adorned with delicate white crystal work for a graceful and sophisticated look. Perfect for everyday elegance and special occasions. Includes matching white scarf.",
    price: 99,
    currency: "AED",
    colours: [variant("grey", "Grey", "#6e6963", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Front-open",
    sleeve: "Straight",
    occasion: ["Everyday", "Eid"],
    embroideryType: "None",
    embellishmentType: "White crystal work",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("/images/products/white-crystal-work-front/1.jpeg", "White Crystal Work Abaya, front view", "portrait"),
      img("/images/products/white-crystal-work-front/2.jpeg", "White Crystal Work Abaya, detail view", "portrait"),
      img("/images/products/white-crystal-work-front/3.jpeg", "White Crystal Work Abaya, detail view", "portrait"),
    ],
    relatedProductIds: ["p-crystal-work-open", "p-black-textured"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open silhouette", "Crystal work detailing", "Includes matching scarf"],
    accuracyTag: "representative",
  },
  {
    id: "p-crystal-work-open",
    slug: "crystal-work-open-abaya",
    name: "Crystal Work Open Abaya",
    collectionSlug: "signature-abayas",
    description: "Black open abaya with stunning white crystal floral embroidery, includes matching white scarf.",
    editorialDescription:
      "Elegant black open abaya featuring stunning white crystal floral embroidery for a graceful and sophisticated look. Perfect for Eid, parties, and special occasions. Includes matching white scarf.",
    price: 99,
    currency: "AED",
    colours: [variant("black", "Black", "#0d0d0d", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Open front",
    sleeve: "Straight",
    occasion: ["Eid", "Evening"],
    embroideryType: "White crystal floral embroidery",
    embellishmentType: "Crystal work",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("/images/products/crystal-work-open-front/1.jpeg", "Crystal Work Open Abaya, front view", "portrait"),
      img("/images/products/crystal-work-open-front/2.jpeg", "Crystal Work Open Abaya, detail view", "portrait"),
    ],
    videos: [
      "/images/products/crystal-work-open-front/v1.mp4",
      "/images/products/crystal-work-open-front/v2.mp4",
    ],
    relatedProductIds: ["p-white-crystal-work", "p-black-floral-pink"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Open-front silhouette", "Crystal floral embroidery", "Includes matching scarf"],
    accuracyTag: "representative",
  },
  {
    id: "p-reversible-brown-pink",
    slug: "reversible-abaya-brown-pink",
    name: "Reversible 2-in-1 Abaya",
    collectionSlug: "signature-abayas",
    description: "Reversible abaya, two colours in one design — brown and pink.",
    editorialDescription:
      "Elegant reversible abaya featuring two beautiful colors in one design. Made from soft, flowy fabric for a comfortable and modest look, perfect for everyday wear and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("brown-pink", "Brown / Pink", "#8a5a44", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Reversible",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [3, 1, 2].map((n) =>
      img(`/images/products/reversible-abaya-brown-pink/${n}.jpeg`, "Reversible 2-in-1 Abaya, brown and pink, view " + n, "portrait")
    ),
    relatedProductIds: ["p-reversible-blue-purple", "p-brown-one-piece-scarf"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Reversible construction, two wearable colourways", "Soft, flowy fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-reversible-blue-purple",
    slug: "reversible-abaya-blue-purple",
    name: "Reversible 2-in-1 Abaya",
    collectionSlug: "signature-abayas",
    description: "Reversible abaya, two colours in one design — blue and purple, with matching scarf.",
    editorialDescription:
      "Stylish reversible abaya with two elegant colors in one design. Made from soft, flowy fabric and paired with a matching scarf for a modest, versatile look.",
    price: 99,
    currency: "AED",
    colours: [variant("blue-purple", "Blue / Purple", "#4b4a7a", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Reversible",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3].map((n) =>
      img(`/images/products/reversible-abaya-blue-purple/${n}.jpeg`, "Reversible 2-in-1 Abaya, blue and purple, view " + n, "portrait")
    ),
    relatedProductIds: ["p-reversible-brown-pink", "p-brown-one-piece-scarf"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Reversible construction, two wearable colourways", "Includes matching scarf"],
    accuracyTag: "representative",
  },
  {
    id: "p-brown-one-piece-scarf",
    slug: "brown-one-piece-abaya-scarf",
    name: "Brown One-Piece Abaya with Scarf",
    collectionSlug: "signature-abayas",
    description: "One-piece abaya with floral print, paired with a matching scarf.",
    editorialDescription:
      "Elegant one-piece abaya with a beautiful floral print, paired with a matching scarf. Soft, comfortable fabric and a modest fit make it perfect for everyday wear and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("brown", "Brown", "#4a3327", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Floral print",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/brown-one-piece-abaya-scarf/1.jpeg", "Brown One-Piece Abaya with Scarf, front view", "portrait")],
    relatedProductIds: ["p-reversible-brown-pink", "p-elegant-floral-open"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Straight one-piece cut", "Floral print fabric", "Includes matching scarf"],
    accuracyTag: "representative",
  },
  {
    id: "p-elegant-floral-open",
    slug: "elegant-floral-open-abaya",
    name: "Elegant Floral Open Abaya",
    collectionSlug: "signature-abayas",
    description: "Floral open abaya, cream base with taupe floral print and pom-pom trim.",
    editorialDescription:
      "Grace your wardrobe with this beautifully designed floral open abaya, featuring a soft cream base, delicate taupe floral print, and elegant pom-pom trim. Made from lightweight, flowy fabric for all-day comfort, it's perfect for everyday wear, gatherings, and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("cream-taupe", "Cream / Taupe", "#f0e6d8", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Open front",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Floral print, pom-pom trim",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5].map((n) =>
      img(`/images/products/elegant-floral-open-abaya/${n}.jpeg`, "Elegant Floral Open Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-brown-one-piece-scarf", "p-elegant-light-pink"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Open-front silhouette", "Lightweight, flowy fabric", "Pom-pom trim"],
    accuracyTag: "representative",
  },
  {
    id: "p-elegant-light-pink",
    slug: "elegant-light-pink-abaya",
    name: "Elegant Light Pink Abaya",
    collectionSlug: "signature-abayas",
    description: "Light pink abaya with crystal stud work, includes matching hijab.",
    editorialDescription:
      "Soft, flowy light pink abaya featuring sparkling crystal stud work on the front and cuffs, complete with a matching hijab for an effortlessly stylish modest look.",
    price: 99,
    currency: "AED",
    colours: [variant("light-pink", "Light Pink", "#f2c9d1", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Straight",
    sleeve: "Cuffed",
    occasion: ["Everyday", "Eid"],
    embroideryType: "None",
    embellishmentType: "Crystal stud work, front and cuffs",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5].map((n) =>
      img(`/images/products/elegant-light-pink-abaya/${n}.jpeg`, "Elegant Light Pink Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-blush-pink-embellished", "p-elegant-floral-open"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Straight cut", "Crystal stud cuffs", "Includes matching hijab"],
    accuracyTag: "representative",
  },
  {
    id: "p-black-nida-brown",
    slug: "black-nida-embroidered-abaya-brown",
    name: "Black Nida Embroidered Abaya",
    collectionSlug: "signature-abayas",
    description: "Black nida abaya with brown floral embroidery and intricate threadwork.",
    editorialDescription:
      "Elegant black abaya featuring beautiful brown floral embroidery with intricate threadwork, creating a sophisticated and modern look. Crafted from premium, flowy fabric with a relaxed fit, it's perfect for everyday elegance, gatherings, and special occasions.",
    price: 120,
    currency: "AED",
    colours: [variant("black-brown", "Black / Brown Embroidery", "#0d0d0d", "matte-nida")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "Front-open",
    sleeve: "Straight",
    occasion: ["Everyday", "Eid"],
    embroideryType: "Brown floral embroidery, intricate threadwork",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [4, 1, 2, 3].map((n) =>
      img(`/images/products/black-nida-embroidered-abaya-brown/${n}.jpeg`, "Black Nida Embroidered Abaya, brown embroidery, view " + n, "portrait")
    ),
    relatedProductIds: ["p-black-nida-blue", "p-black-nida-silver"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open nida silhouette", "Relaxed fit", "Threadwork embroidery"],
    accuracyTag: "representative",
  },
  {
    id: "p-black-textured",
    slug: "black-textured-abaya",
    name: "Black Textured Abaya",
    collectionSlug: "signature-abayas",
    description: "Black abaya in premium textured fabric with a shawl collar and butterfly-shaped crystal buttons.",
    editorialDescription:
      "Elegant black abaya crafted from premium textured fabric, featuring a sophisticated shawl collar and delicate butterfly-shaped crystal buttons. A timeless design with a graceful flow, perfect for everyday elegance or special occasions. Available in multiple sizes.",
    price: 99,
    currency: "AED",
    colours: [variant("black", "Black", "#0d0d0d", "jacquard")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "jacquard",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday", "Work"],
    embroideryType: "None",
    embellishmentType: "Butterfly-shaped crystal buttons",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5].map((n) =>
      img(`/images/products/black-textured-abaya/${n}.jpeg`, "Black Textured Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-white-crystal-work", "p-classic-black-lace"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Shawl collar", "Textured weave", "Crystal button closures"],
    accuracyTag: "representative",
  },
  {
    id: "p-classic-black-lace",
    slug: "classic-black-lace-abaya",
    name: "Classic Black Lace Abaya",
    collectionSlug: "signature-abayas",
    description: "Black abaya with intricate lace detailing along the front panel, neckline and sleeve cuffs.",
    editorialDescription:
      "Elegant black abaya featuring intricate lace detailing along the front panel, neckline, and sleeve cuffs for a sophisticated, timeless look. Crafted from premium, flowy fabric with a graceful silhouette, it offers all-day comfort and effortless elegance — perfect for everyday wear, gatherings, and special occasions.",
    price: 109,
    currency: "AED",
    colours: [variant("black", "Black", "#0d0d0d", "lace")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "lace",
    cut: "Front-open",
    sleeve: "Cuffed",
    occasion: ["Everyday", "Eid"],
    embroideryType: "None",
    embellishmentType: "Lace detailing, front panel, neckline and cuffs",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4].map((n) =>
      img(`/images/products/classic-black-lace-abaya/${n}.jpeg`, "Classic Black Lace Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-charcoal-grey-lace", "p-black-textured"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open silhouette", "Lace trim at neckline and cuffs", "Graceful drape"],
    accuracyTag: "representative",
  },
  {
    id: "p-blush-pink-embellished",
    slug: "blush-pink-embellished-abaya",
    name: "Blush Pink Embellished Abaya",
    collectionSlug: "signature-abayas",
    description: "Blush pink front-open abaya with crystal floral embellishments on the hem and sleeve cuffs.",
    editorialDescription:
      "Elegant blush pink front-open abaya featuring delicate crystal floral embellishments on the hem and sleeve cuffs. Crafted from premium, flowy fabric with a graceful silhouette, it offers a perfect blend of elegance and comfort — ideal for Eid, weddings, parties, and special occasions.",
    price: 120,
    currency: "AED",
    colours: [variant("blush-pink", "Blush Pink", "#eeccd0", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Front-open",
    sleeve: "Cuffed",
    occasion: ["Eid", "Wedding", "Evening"],
    embroideryType: "None",
    embellishmentType: "Crystal floral embellishment, hem and cuffs",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5].map((n) =>
      img(`/images/products/blush-pink-embellished-abaya/${n}.jpeg`, "Blush Pink Embellished Abaya, view " + n, "portrait")
    ),
    isFeatured: true,
    relatedProductIds: ["p-elegant-light-pink", "p-premium-floral-embellished"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open silhouette", "Crystal embellishment at hem and cuffs", "Premium flowy fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-black-floral-red",
    slug: "black-floral-embroidered-abaya-red",
    name: "Black Floral Embroidered Abaya",
    collectionSlug: "signature-abayas",
    description: "Black front-open abaya with striking red floral embroidery along the front and sleeves.",
    editorialDescription:
      "Elegant black front-open abaya featuring striking red floral embroidery along the front and sleeves for a bold yet graceful look. Crafted from premium, flowy fabric with a relaxed fit, it offers timeless elegance and all-day comfort — perfect for everyday wear, gatherings, and special occasions.",
    price: 120,
    currency: "AED",
    colours: [variant("black-red", "Black / Red Embroidery", "#0d0d0d", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Front-open",
    sleeve: "Straight",
    occasion: ["Everyday", "Eid"],
    embroideryType: "Red floral embroidery, front and sleeves",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("/images/products/black-floral-red-front/1.jpeg", "Black Floral Embroidered Abaya, red embroidery, front view", "portrait"),
      img("/images/products/black-floral-red-front/2.jpeg", "Black Floral Embroidered Abaya, red embroidery, detail view", "portrait"),
      img("/images/products/black-floral-red-front/3.jpeg", "Black Floral Embroidered Abaya, red embroidery, detail view", "portrait"),
      img("/images/products/black-floral-red-front/4.jpeg", "Black Floral Embroidered Abaya, red embroidery, detail view", "portrait"),
    ],
    videos: ["/images/products/black-floral-red-front/v1.mp4"],
    relatedProductIds: ["p-black-floral-pink", "p-black-nida-brown"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open silhouette", "Relaxed fit", "Bold floral embroidery"],
    accuracyTag: "representative",
  },
  {
    id: "p-charcoal-grey-lace",
    slug: "charcoal-grey-lace-abaya",
    name: "Charcoal Grey Lace Abaya",
    collectionSlug: "signature-abayas",
    description: "Charcoal grey front-open abaya with intricate lace detailing along the front and sleeve cuffs.",
    editorialDescription:
      "Elegant charcoal grey front-open abaya featuring intricate lace detailing along the front and sleeve cuffs. Crafted from premium, flowy fabric with a graceful silhouette, it offers timeless sophistication and all-day comfort — perfect for everyday wear, gatherings, and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("charcoal", "Charcoal Grey", "#3a3a3a", "lace")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "lace",
    cut: "Front-open",
    sleeve: "Cuffed",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Lace detailing, front and cuffs",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3].map((n) =>
      img(`/images/products/charcoal-grey-lace-abaya/${n}.jpeg`, "Charcoal Grey Lace Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-classic-black-lace", "p-white-crystal-work"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open silhouette", "Lace trim at cuffs", "Graceful drape"],
    accuracyTag: "representative",
  },
  {
    id: "p-sage-green-kaftan",
    slug: "sage-green-embroidered-kaftan-abaya",
    name: "Sage Green Embroidered Kaftan Abaya",
    collectionSlug: "signature-abayas",
    description: "Sage green kaftan-style abaya with floral embroidery on the front and sleeves.",
    editorialDescription:
      "Graceful sage green kaftan-style abaya featuring elegant floral embroidery on the front and sleeves. Crafted from soft, flowy fabric with a relaxed fit, it offers both comfort and sophistication — perfect for everyday elegance, Ramadan, Eid, and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("sage-green", "Sage Green", "#9caf88", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Kaftan",
    sleeve: "Flared",
    occasion: ["Ramadan", "Eid", "Everyday"],
    embroideryType: "Floral embroidery, front and sleeves",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3].map((n) =>
      img(`/images/products/sage-green-embroidered-kaftan-abaya/${n}.jpeg`, "Sage Green Embroidered Kaftan Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-luxury-kaftan", "p-elegant-floral-open"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Kaftan silhouette", "Relaxed fit", "Floral embroidery, front and sleeves"],
    accuracyTag: "representative",
  },
  {
    id: "p-black-nida-blue",
    slug: "black-nida-embroidered-abaya-blue",
    name: "Black Nida Abaya",
    collectionSlug: "signature-abayas",
    description: "Black front-open nida abaya with delicate blue floral embroidery on the sleeves and hem.",
    editorialDescription:
      "Elegant black front-open abaya featuring delicate blue floral embroidery on the sleeves and hem. Designed with a comfortable, flowing silhouette and premium fabric, making it perfect for everyday wear, gatherings, and special occasions. A timeless blend of modesty and sophistication.",
    price: 120,
    currency: "AED",
    colours: [variant("black-blue", "Black / Blue Embroidery", "#0d0d0d", "matte-nida")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "Front-open",
    sleeve: "Straight",
    occasion: ["Everyday", "Eid"],
    embroideryType: "Blue floral embroidery, sleeves and hem",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5, 6].map((n) =>
      img(`/images/products/black-nida-embroidered-abaya-blue/${n}.jpeg`, "Black Nida Abaya, blue embroidery, view " + n, "portrait")
    ),
    relatedProductIds: ["p-black-nida-brown", "p-black-nida-silver"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Front-open nida silhouette", "Flowing drape", "Blue floral embroidery"],
    accuracyTag: "representative",
  },
  {
    id: "p-black-nida-silver",
    slug: "black-nida-abaya-silver-stripe",
    name: "Black Nida Abaya",
    collectionSlug: "signature-abayas",
    description: "Black nida abaya with stylish silver stripe detailing, soft and lightweight.",
    editorialDescription:
      "Elegant black Nida abaya featuring stylish silver stripe detailing. Made from soft, lightweight, and breathable fabric for all-day comfort. Perfect for everyday wear and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("black-silver", "Black / Silver Stripe", "#0d0d0d", "matte-nida")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "matte-nida",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday", "Travel"],
    embroideryType: "None",
    embellishmentType: "Silver stripe detailing",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3].map((n) =>
      img(`/images/products/black-nida-abaya-silver-stripe/${n}.jpeg`, "Black Nida Abaya, silver stripe, view " + n, "portrait")
    ),
    relatedProductIds: ["p-black-nida-blue", "p-black-nida-brown"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Straight nida silhouette", "Lightweight, breathable fabric", "Silver stripe trim"],
    accuracyTag: "representative",
  },
  {
    id: "p-luxury-kaftan",
    slug: "luxury-kaftan-abaya",
    name: "Luxury Kaftan Abaya",
    collectionSlug: "signature-abayas",
    description: "White chiffon kaftan with pink floral embroidery, gold beaded accents and draped cape sleeves.",
    editorialDescription:
      "Pristine white chiffon kaftan abaya featuring delicate pink floral embroidery, gold beaded accents, and draped cape sleeves with fine gold trim. Includes a matching Sheila — ideal for Eid, weddings, and formal events. DM to order.",
    price: 150,
    currency: "AED",
    colours: [variant("white-gold", "White / Gold", "#f7f3e8", "chiffon-overlay")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "chiffon-overlay",
    cut: "Kaftan",
    sleeve: "Cape",
    occasion: ["Eid", "Wedding", "Evening"],
    embroideryType: "Pink floral embroidery",
    embellishmentType: "Gold beaded accents, gold trim",
    care: ["Dry clean only", "Store flat or on a padded hanger", "Handle beaded trim with care"],
    availability: "made-to-order",
    images: [1, 2, 3].map((n) =>
      img(`/images/products/luxury-kaftan-abaya/${n}.jpeg`, "Luxury Kaftan Abaya, view " + n, "portrait")
    ),
    isFeatured: true,
    isLimited: true,
    relatedProductIds: ["p-sage-green-kaftan", "p-blush-pink-embellished"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Kaftan silhouette with draped cape sleeves", "Gold trim", "Includes matching Sheila", "Made to order — DM to confirm timeline"],
    accuracyTag: "representative",
  },

  // ---------- Three-Piece Sets ----------
  {
    id: "p-three-piece-beige",
    slug: "elegant-three-piece-abaya-set-beige",
    name: "Elegant 3-Piece Abaya Set",
    collectionSlug: "three-piece-sets",
    description: "Timeless 3-piece abaya in soft beige with delicate lace detailing. Outer abaya, inner dress & scarf.",
    editorialDescription:
      "A timeless 3-piece abaya in a soft beige shade with delicate lace detailing for a graceful and refined look. Perfect for everyday elegance and special occasions. Includes outer abaya, inner dress & matching scarf.",
    price: 99,
    currency: "AED",
    colours: [variant("beige", "Beige", "#d9c9b5", "lace")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "lace",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Everyday", "Eid"],
    embroideryType: "None",
    embellishmentType: "Lace detailing",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5].map((n) =>
      img(`/images/products/elegant-three-piece-abaya-set-beige/${n}.jpeg`, "Elegant 3-Piece Abaya Set, beige, view " + n, "portrait")
    ),
    relatedProductIds: ["p-three-piece-lavender", "p-three-piece-floral"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Outer abaya + inner dress + matching scarf", "Lace detailing", "Refined, graceful drape"],
    accuracyTag: "representative",
  },
  {
    id: "p-three-piece-lavender",
    slug: "elegant-three-piece-abaya-set-lavender",
    name: "Elegant 3-Piece Abaya Set",
    collectionSlug: "three-piece-sets",
    description: "Graceful 3-piece abaya in lavender and white with floral embroidery. Open abaya, inner dress & scarf.",
    editorialDescription:
      "A graceful 3-piece abaya in a beautiful lavender and white combination with delicate floral embroidery. Perfect for Eid, gatherings, and special occasions. Includes open abaya, inner dress & matching white scarf.",
    price: 99,
    currency: "AED",
    colours: [variant("lavender-white", "Lavender / White", "#b9a9c9", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Eid", "Everyday"],
    embroideryType: "Floral embroidery",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4].map((n) =>
      img(`/images/products/elegant-three-piece-abaya-set-lavender/${n}.jpeg`, "Elegant 3-Piece Abaya Set, lavender, view " + n, "portrait")
    ),
    isNew: true,
    relatedProductIds: ["p-three-piece-beige", "p-three-piece-white-mocha-leaf"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Open abaya + inner dress + matching scarf", "Floral embroidery", "Lavender and white combination"],
    accuracyTag: "representative",
  },
  {
    id: "p-three-piece-floral",
    slug: "elegant-three-piece-abaya-floral",
    name: "Elegant 3-Piece Abaya",
    collectionSlug: "three-piece-sets",
    description: "3-piece abaya set with soft floral print and premium flowy fabric.",
    editorialDescription:
      "Beautiful 3-piece abaya set featuring a soft floral print and premium flowy fabric. Perfect for everyday elegance and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("floral", "Floral Print", "#e6c9d6", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Floral print",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3].map((n) =>
      img(`/images/products/elegant-three-piece-abaya-floral/${n}.jpeg`, "Elegant 3-Piece Abaya, floral print, view " + n, "portrait")
    ),
    relatedProductIds: ["p-three-piece-beige", "p-three-piece-lavender"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Three-piece set", "Soft floral print", "Premium flowy fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-maroon-three-piece",
    slug: "maroon-three-piece-embroidered-abaya-set",
    name: "Maroon Three-Piece Embroidery Abaya Set",
    collectionSlug: "three-piece-sets",
    description: "Open abaya in rich maroon with taupe shawl collar and black floral embroidery on the shoulders.",
    editorialDescription:
      "Elegant open abaya in a rich maroon shade with a taupe shawl collar and sleeves, featuring beautiful black floral embroidery on the shoulders. Finished with a stylish front pendant for a graceful look.",
    price: 99,
    currency: "AED",
    colours: [variant("maroon-taupe", "Maroon / Taupe", "#5c1a2b", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Eid", "Everyday"],
    embroideryType: "Black floral embroidery, shoulders",
    embellishmentType: "Front pendant",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4].map((n) =>
      img(`/images/products/maroon-three-piece-embroidered-abaya-set/${n}.jpeg`, "Maroon Three-Piece Embroidery Abaya Set, view " + n, "portrait")
    ),
    relatedProductIds: ["p-three-piece-black-mocha", "p-three-piece-white-mocha-leaf"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Taupe shawl collar and sleeves", "Black floral embroidery at shoulders", "Front pendant detail"],
    accuracyTag: "representative",
  },
  {
    id: "p-three-piece-white-embroidered",
    slug: "three-piece-white-embroidered-abaya-set",
    name: "Three-Piece White Embroidered Abaya Set",
    collectionSlug: "three-piece-sets",
    description: "White three-piece set: embroidered outer abaya, matching inner dress and coordinating hijab.",
    editorialDescription:
      "Elegant three-piece abaya set featuring a beautifully embroidered white outer abaya, a matching inner dress, and a coordinating hijab. Crafted from premium, flowy fabric with delicate floral embroidery, this timeless set offers comfort, modesty, and sophistication — perfect for Eid, weddings, gatherings, and special occasions or daily wear. Price on request — DM to confirm current pricing.",
    price: 99,
    currency: "AED",
    colours: [variant("white", "White", "#f5f2ec", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Eid", "Wedding", "Everyday"],
    embroideryType: "Floral embroidery",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "made-to-order",
    images: [img("/images/products/three-piece-white-embroidered-abaya-set/1.png", "Three-Piece White Embroidered Abaya Set, front view", "portrait")],
    relatedProductIds: ["p-three-piece-white-mocha-leaf", "p-three-piece-beige"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: [
      "Embroidered outer abaya + matching inner dress + coordinating hijab",
      "Floral embroidery",
      "No listed catalog price — confirm with supplier before publishing live",
    ],
    accuracyTag: "unverified",
  },
  {
    id: "p-three-piece-black-mocha",
    slug: "three-piece-embroidered-abaya-set-black-mocha",
    name: "Three-Piece Embroidered Abaya Set",
    collectionSlug: "three-piece-sets",
    description: "Black embroidered outer abaya with a matching mocha inner dress and coordinating accents.",
    editorialDescription:
      "Elegant three-piece abaya set featuring a black embroidered outer abaya with intricate floral embroidery, a matching mocha inner dress, and coordinating outer accents. Crafted from premium, flowy fabric, this set offers timeless elegance, comfort, and modesty — perfect for everyday wear, gatherings, Eid, and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("black-mocha", "Black / Mocha", "#0d0d0d", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Eid", "Everyday"],
    embroideryType: "Floral embroidery, outer abaya",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3].map((n) =>
      img(`/images/products/three-piece-embroidered-abaya-set-black-mocha/${n}.jpeg`, "Three-Piece Embroidered Abaya Set, black and mocha, view " + n, "portrait")
    ),
    relatedProductIds: ["p-maroon-three-piece", "p-three-piece-white-mocha-leaf"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Outer abaya + mocha inner dress + coordinating accents", "Floral embroidery", "Premium flowy fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-three-piece-white-mocha-leaf",
    slug: "three-piece-abaya-set-white-mocha-leaf",
    name: "Three Piece Abaya Set",
    collectionSlug: "three-piece-sets",
    description: "White and mocha 3-piece set with leaf embroidery: outer abaya, inner dress and hijab.",
    editorialDescription:
      "Elegant three-piece abaya set featuring a stylish outer abaya, matching inner dress, and coordinating hijab. Designed in a timeless white and mocha color combination with beautiful leaf embroidery, this premium set offers comfort, modesty, and sophistication — perfect for everyday wear, Eid, gatherings, and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("white-mocha", "White / Mocha", "#e6dccb", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Eid", "Everyday"],
    embroideryType: "Leaf embroidery",
    embellishmentType: "Thread embroidery",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5].map((n) =>
      img(`/images/products/three-piece-abaya-set-white-mocha-leaf/${n}.jpeg`, "Three Piece Abaya Set, white and mocha, view " + n, "portrait")
    ),
    relatedProductIds: ["p-three-piece-lavender", "p-three-piece-black-mocha"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Outer abaya + inner dress + coordinating hijab", "Leaf embroidery", "White and mocha combination"],
    accuracyTag: "representative",
  },

  // ---------- Added from live catalog re-sync (2026-08-06) ----------
  {
    id: "p-sage-green-handwork",
    slug: "sage-green-handwork-abaya",
    name: "Sage Green Handwork Abaya",
    collectionSlug: "signature-abayas",
    description: "Sage green abaya with beautiful floral handwork on the hem and sleeves.",
    editorialDescription:
      "Elegant sage green abaya featuring beautiful floral handwork on the hem and sleeves. Made from soft, flowy fabric for a graceful and comfortable fit — perfect for everyday wear and special occasions.",
    price: 120,
    currency: "AED",
    colours: [variant("sage-green", "Sage Green", "#9caf88", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "Floral handwork, hem and sleeves",
    embellishmentType: "None",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5, 6].map((n) =>
      img(`/images/products/sage-green-handwork-abaya/${n}.jpeg`, "Sage Green Handwork Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-sage-green-kaftan", "p-sage-green-three-piece"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Soft, flowy fabric", "Floral handwork at hem and sleeves"],
    accuracyTag: "representative",
  },
  {
    id: "p-classic-maroon",
    slug: "classic-maroon-abaya",
    name: "Classic Maroon Abaya",
    collectionSlug: "signature-abayas",
    description: "Timeless maroon abaya with a graceful flow, elegant lapel collar and decorative button details.",
    editorialDescription:
      "A timeless maroon abaya designed with a graceful flow and elegant lapel collar, finished with delicate decorative button details. Crafted from premium fabric for all-day comfort, making it a perfect choice for everyday wear and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("maroon", "Maroon", "#5c1a2b", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Decorative button details, lapel collar",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5, 6].map((n) =>
      img(`/images/products/classic-maroon-abaya/${n}.jpeg`, "Classic Maroon Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-maroon-three-piece", "p-classic-black-lace"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Elegant lapel collar", "Decorative button details", "Premium fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-navy-blue",
    slug: "navy-blue-abaya",
    name: "Navy Blue Abaya",
    collectionSlug: "signature-abayas",
    description: "Navy blue abaya with luxurious gold trim and stylish layered flared sleeves.",
    editorialDescription:
      "Elegant navy blue abaya with luxurious gold trim and stylish layered flared sleeves. Crafted from soft, flowy fabric for a graceful and comfortable fit.",
    price: 125,
    currency: "AED",
    colours: [variant("navy", "Navy Blue", "#1b2a4a", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Straight",
    sleeve: "Flared",
    occasion: ["Everyday", "Evening"],
    embroideryType: "None",
    embellishmentType: "Gold trim, layered flared sleeves",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3].map((n) =>
      img(`/images/products/navy-blue-abaya/${n}.jpeg`, "Navy Blue Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-elegant-black", "p-classy-peach"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Gold trim", "Layered flared sleeves", "Soft, flowy fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-three-piece-printed",
    slug: "three-piece-printed-abaya-set",
    name: "3 Piece Printed Abaya",
    collectionSlug: "three-piece-sets",
    description: "3-piece printed abaya set: open abaya, matching inner dress and coordinating scarf.",
    editorialDescription:
      "Elevate your modest wardrobe with this beautiful 3-piece printed abaya set, featuring a stylish open abaya, matching inner dress, and coordinating scarf. Made from soft, premium fabric with a graceful flow, it's perfect for everyday wear and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("printed", "Printed", "#c9b8a8", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Printed fabric",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4].map((n) =>
      img(`/images/products/three-piece-printed-abaya-set/${n}.jpeg`, "3 Piece Printed Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-three-piece-beige", "p-sage-green-three-piece"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Open abaya + inner dress + coordinating scarf", "Printed fabric", "Soft, premium fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-soft-blush-pink",
    slug: "soft-blush-pink-abaya",
    name: "Soft Blush Pink Abaya",
    collectionSlug: "signature-abayas",
    description: "Flowing blush pink abaya with shimmering golden lace detailing.",
    editorialDescription:
      "Grace meets simplicity with this flowing blush pink abaya, beautifully finished with shimmering golden lace detailing for a refined and graceful look. Perfect for everyday elegance or special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("blush-pink", "Blush Pink", "#eeccd0", "lace")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "lace",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Golden lace detailing",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/soft-blush-pink-abaya/1.jpeg", "Soft Blush Pink Abaya, front view", "portrait")],
    relatedProductIds: ["p-blush-pink-embellished", "p-elegant-light-pink"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Flowing silhouette", "Golden lace detailing"],
    accuracyTag: "representative",
  },
  {
    id: "p-dark-brown",
    slug: "dark-brown-abaya",
    name: "Dark Brown Abaya",
    collectionSlug: "signature-abayas",
    description: "Classic dark brown abaya with a graceful flow and stylish button detailing.",
    editorialDescription:
      "Classic dark brown abaya with a graceful flow and stylish button detailing. Crafted from soft fabric for all-day comfort, making it a perfect choice for everyday wear and special occasions.",
    price: 99,
    currency: "AED",
    colours: [variant("dark-brown", "Dark Brown", "#3b2a20", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Button detailing",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4].map((n) =>
      img(`/images/products/dark-brown-abaya/${n}.jpeg`, "Dark Brown Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-brown-one-piece-scarf", "p-black-nida-brown"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Graceful flow", "Button detailing", "Soft fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-black-embroidered",
    slug: "black-embroidered-abaya",
    name: "Black Embroidered Abaya",
    collectionSlug: "signature-abayas",
    description: "Black abaya with intricate embroidery on the sleeves and sides, finished with contrast piping.",
    editorialDescription:
      "Beautiful black abaya featuring intricate embroidery on the sleeves and sides, finished with contrast piping for a refined look. Crafted from soft, flowy fabric for all-day comfort.",
    price: 99,
    currency: "AED",
    colours: [variant("black", "Black", "#0d0d0d", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday", "Eid"],
    embroideryType: "Embroidery, sleeves and sides",
    embellishmentType: "Contrast piping",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5, 6].map((n) =>
      img(`/images/products/black-embroidered-abaya/${n}.jpeg`, "Black Embroidered Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-classic-black-lace", "p-black-textured"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Embroidery at sleeves and sides", "Contrast piping", "Soft, flowy fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-light-brown-embellished",
    slug: "light-brown-embellished-abaya",
    name: "Light Brown Embellished Abaya",
    collectionSlug: "signature-abayas",
    description: "Light brown abaya with sparkling crystal embellishments and flowy umbrella sleeves.",
    editorialDescription:
      "Beautiful light brown abaya featuring sparkling crystal embellishments with delicate floral detailing. Designed with flowy umbrella sleeves and a graceful flare for a modest, elegant look.",
    price: 99,
    currency: "AED",
    colours: [variant("light-brown", "Light Brown", "#a67b5b", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Straight",
    sleeve: "Flared",
    occasion: ["Everyday", "Eid"],
    embroideryType: "None",
    embellishmentType: "Crystal embellishments, floral detailing",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4].map((n) =>
      img(`/images/products/light-brown-embellished-abaya/${n}.jpeg`, "Light Brown Embellished Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-classy-peach", "p-dark-brown"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Flowy umbrella sleeves", "Crystal embellishments", "Graceful flare"],
    accuracyTag: "representative",
  },
  {
    id: "p-sage-green-three-piece",
    slug: "sage-green-three-piece-abaya-set",
    name: "Sage Green 3-Piece Abaya",
    collectionSlug: "three-piece-sets",
    description: "3-piece abaya set with a graceful floral print outer layer, matching inner dress and scarf.",
    editorialDescription:
      "A beautiful 3-piece abaya set featuring a graceful floral print outer layer with a matching inner dress and scarf. Soft, flowy fabric offers a stylish and modest look for every occasion.",
    price: 110,
    currency: "AED",
    colours: [variant("sage-green", "Sage Green", "#9caf88", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Open front",
    sleeve: "Layered",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Floral print",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4].map((n) =>
      img(`/images/products/sage-green-three-piece-abaya-set/${n}.jpeg`, "Sage Green 3-Piece Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-sage-green-handwork", "p-three-piece-printed"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Outer layer + inner dress + scarf", "Floral print", "Soft, flowy fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-elegant-black",
    slug: "elegant-black-abaya",
    name: "Elegant Black Abaya",
    collectionSlug: "signature-abayas",
    description: "Elegant black abaya with gold trim and stylish flared sleeves.",
    editorialDescription:
      "Elegant black abaya with gold trim and stylish flared sleeves. Made from soft, flowy fabric for a graceful and comfortable fit.",
    price: 125,
    currency: "AED",
    colours: [variant("black", "Black", "#0d0d0d", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Straight",
    sleeve: "Flared",
    occasion: ["Everyday", "Evening"],
    embroideryType: "None",
    embellishmentType: "Gold trim",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2].map((n) =>
      img(`/images/products/elegant-black-abaya/${n}.jpeg`, "Elegant Black Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-navy-blue", "p-classy-peach"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Gold trim", "Flared sleeves", "Soft, flowy fabric"],
    accuracyTag: "representative",
  },
  {
    id: "p-classy-peach",
    slug: "classy-peach-abaya",
    name: "Classy Peach Abaya",
    collectionSlug: "signature-abayas",
    description: "Classy peach abaya with elegant gold detailing and statement flared sleeves.",
    editorialDescription:
      "A classy peach abaya with elegant gold detailing and statement flared sleeves, designed to offer a graceful, luxurious look. Perfect for occasions and sophisticated everyday wear.",
    price: 125,
    currency: "AED",
    colours: [variant("peach", "Peach", "#e8b896", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Straight",
    sleeve: "Flared",
    occasion: ["Everyday", "Evening"],
    embroideryType: "None",
    embellishmentType: "Gold detailing, statement flared sleeves",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [1, 2, 3, 4, 5].map((n) =>
      img(`/images/products/classy-peach-abaya/${n}.jpeg`, "Classy Peach Abaya, view " + n, "portrait")
    ),
    relatedProductIds: ["p-navy-blue", "p-elegant-black"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Gold detailing", "Statement flared sleeves", "Luxurious drape"],
    accuracyTag: "representative",
  },
  {
    id: "p-black-lace",
    slug: "black-lace-abaya",
    name: "Black Lace Abaya",
    collectionSlug: "signature-abayas",
    description: "Black abaya with delicate floral lace detailing on the sleeves and front.",
    editorialDescription:
      "Beautiful black abaya featuring delicate floral lace detailing on the sleeves and front, creating a graceful and timeless look.",
    price: 90,
    currency: "AED",
    colours: [variant("black", "Black", "#0d0d0d", "lace")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "lace",
    cut: "Straight",
    sleeve: "Straight",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Floral lace detailing, sleeves and front",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/black-lace-abaya/1.jpeg", "Black Lace Abaya, front view", "portrait")],
    relatedProductIds: ["p-classic-black-lace", "p-white-lace"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Floral lace detailing", "Timeless silhouette"],
    accuracyTag: "representative",
  },
  {
    id: "p-white-lace",
    slug: "white-lace-abaya",
    name: "White Lace Abaya",
    collectionSlug: "signature-abayas",
    description: "White abaya with beautiful lace sleeves and delicate floral embroidery.",
    editorialDescription:
      "Elegant white abaya with beautiful lace sleeves and delicate floral embroidery. Crafted from soft, flowy fabric for a graceful and modest look.",
    price: 90,
    currency: "AED",
    colours: [variant("white", "White", "#f5f2ec", "lace")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "lace",
    cut: "Straight",
    sleeve: "Cuffed",
    occasion: ["Everyday"],
    embroideryType: "Floral embroidery",
    embellishmentType: "Lace sleeves",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/white-lace-abaya/1.jpeg", "White Lace Abaya, front view", "portrait")],
    relatedProductIds: ["p-black-lace", "p-luxury-kaftan"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Lace sleeves", "Floral embroidery", "Soft, flowy fabric"],
    accuracyTag: "representative",
  },

  // ---------- Added 2026-08-06: WhatsApp catalog additions ----------
  {
    id: "p-monochrome-polka-dot",
    slug: "monochrome-polka-dot-prayer-dress",
    name: "Monochrome Polka Dot Prayer Dress",
    collectionSlug: "signature-abayas",
    description:
      "Lightweight cotton prayer dress with a classic black polka dot pattern on pure white and an attached matching headscarf.",
    editorialDescription:
      "(Different colors available) Lightweight, breathable cotton prayer dress featuring a classic black polka dot pattern on pure white, elasticated cuffed sleeves, and an attached matching headscarf for effortless coverage.",
    price: 49,
    currency: "AED",
    colours: [variant("white-black-polka", "White / Black Polka Dot", "#f5f2ec", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Relaxed",
    sleeve: "Elasticated cuff",
    occasion: ["Everyday", "Ramadan"],
    embroideryType: "None",
    embellishmentType: "Polka dot print, attached headscarf",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [
      img("/images/products/monochrome-polka-dot-prayer-dress/1.jpg", "Monochrome Polka Dot Prayer Dress, front view", "portrait"),
      img("/images/products/monochrome-polka-dot-prayer-dress/2.jpg", "Monochrome Polka Dot Prayer Dress, fabric detail", "detail"),
    ],
    relatedProductIds: ["p-cotton-prayer-dress"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Free size — to be confirmed with supplier.",
    constructionDetails: ["Attached matching headscarf", "Elasticated cuffed sleeves", "Breathable cotton"],
    accuracyTag: "representative",
  },
  {
    id: "p-mocha-marble",
    slug: "mocha-marble-abaya",
    name: "Mocha Marble Abaya",
    collectionSlug: "signature-abayas",
    description: "Loose full-length abaya with a V-neckline in a fluid mocha and charcoal marble print.",
    editorialDescription:
      "Fit: Loose full-length silhouette with a V-neckline. Fabric: Fluid drape with mocha and charcoal marble texture. Occasion: Ideal for daily wear.",
    price: 45,
    currency: "AED",
    colours: [variant("mocha-charcoal", "Mocha / Charcoal Marble", "#4a3728", "jacquard")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "jacquard",
    cut: "V-neck",
    sleeve: "Long sleeve",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Marble-effect print",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/mocha-marble-abaya/1.jpg", "Mocha Marble Abaya, front view", "portrait")],
    relatedProductIds: ["p-zebra-print", "p-grey-printed"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["V-neckline", "Fluid drape", "Marble-effect print"],
    accuracyTag: "representative",
  },
  {
    id: "p-zebra-print",
    slug: "zebra-print-open-abaya",
    name: "Zebra Print Open Abaya",
    collectionSlug: "signature-abayas",
    description: "Bold beige and black zebra-patterned open front abaya with relaxed bell sleeves.",
    editorialDescription:
      "Bold beige and black zebra-patterned open front abaya with relaxed bell sleeves, perfect for adding a chic statement to any contemporary modest wardrobe.",
    price: 79,
    currency: "AED",
    colours: [variant("beige-black-zebra", "Beige / Black Zebra Print", "#c9a876", "jacquard")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "jacquard",
    cut: "Open front",
    sleeve: "Bell sleeve",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Zebra print",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/zebra-print-open-abaya/1.jpg", "Zebra Print Open Abaya, front view", "portrait")],
    relatedProductIds: ["p-mocha-marble", "p-multicolor-printed"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Open front silhouette", "Relaxed bell sleeves", "Zebra-patterned print"],
    accuracyTag: "representative",
  },
  {
    id: "p-multicolor-printed",
    slug: "multicolor-printed-open-abaya",
    name: "Multicolor Printed Open Abaya",
    collectionSlug: "signature-abayas",
    description: "Open abaya in a maroon, beige and cream abstract swirl print, free size.",
    editorialDescription:
      "A stylish open abaya featuring a beautiful blend of maroon, beige, and cream abstract prints. Made from soft, lightweight fabric with a relaxed fit, it's perfect for everyday wear, casual outings, and special occasions. Free size.",
    price: 79,
    currency: "AED",
    colours: [variant("maroon-beige-cream", "Maroon / Beige / Cream Abstract", "#8a3b4a", "jacquard")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "jacquard",
    cut: "Open front",
    sleeve: "Relaxed",
    occasion: ["Everyday", "Eid"],
    embroideryType: "None",
    embellishmentType: "Abstract swirl print",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/multicolor-printed-open-abaya/1.png", "Multicolor Printed Open Abaya, front view", "portrait")],
    relatedProductIds: ["p-zebra-print", "p-brown-printed"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Free size — to be confirmed with supplier.",
    constructionDetails: ["Open front silhouette", "Relaxed fit", "Abstract multicolor print", "Free size"],
    accuracyTag: "representative",
  },
  {
    id: "p-brown-printed",
    slug: "brown-printed-open-abaya",
    name: "Brown Printed Open Abaya",
    collectionSlug: "signature-abayas",
    description: "Open abaya in a brown shade with an elegant black abstract print.",
    editorialDescription:
      "A timeless open abaya featuring a beautiful brown shade with an elegant black abstract print. Made from soft, lightweight fabric for all-day comfort, it's perfect for everyday wear, casual outings, and special occasions.",
    price: 79,
    currency: "AED",
    colours: [variant("brown-black", "Brown / Black Abstract", "#5c4632", "jacquard")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "jacquard",
    cut: "Open front",
    sleeve: "Relaxed",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Abstract print",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/brown-printed-open-abaya/1.jpg", "Brown Printed Open Abaya, front view", "portrait")],
    relatedProductIds: ["p-grey-printed", "p-multicolor-printed"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Open front silhouette", "Soft, lightweight fabric", "Abstract print"],
    accuracyTag: "representative",
  },
  {
    id: "p-grey-printed",
    slug: "grey-printed-open-abaya",
    name: "Grey Printed Open Abaya",
    collectionSlug: "signature-abayas",
    description: "Open abaya in a grey and black abstract print, available in UAE.",
    editorialDescription:
      "A stylish and elegant open abaya featuring a beautiful grey and black abstract print. Made from soft, comfortable fabric with a relaxed fit, it's perfect for everyday wear, casual outings, or special occasions. Available in UAE.",
    price: 45,
    currency: "AED",
    colours: [variant("grey-black", "Grey / Black Abstract", "#4a4a4a", "jacquard")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "jacquard",
    cut: "Open front",
    sleeve: "Relaxed",
    occasion: ["Everyday"],
    embroideryType: "None",
    embellishmentType: "Abstract print",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/grey-printed-open-abaya/1.jpg", "Grey Printed Open Abaya, front view", "portrait")],
    relatedProductIds: ["p-brown-printed", "p-mocha-marble"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Open front silhouette", "Relaxed, comfortable fit", "Abstract print"],
    accuracyTag: "representative",
  },
  {
    id: "p-metallic-floral-sage",
    slug: "metallic-floral-sage-abaya-set",
    name: "Metallic Floral Sage Abaya Set",
    collectionSlug: "signature-abayas",
    description: "Sage green abaya with shimmering metallic foil floral accents and a matching plain chiffon scarf.",
    editorialDescription:
      "Elegant sage green abaya adorned with shimmering metallic foil floral accents, paired with a matching plain chiffon scarf for a refined, balanced look. Perfect for special occasions and formal gatherings.",
    price: 89,
    currency: "AED",
    colours: [variant("sage-metallic", "Sage Green / Metallic Floral", "#a8b39a", "hand-embroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "hand-embroidered",
    cut: "Front-open",
    sleeve: "Long sleeve",
    occasion: ["Evening", "Wedding", "Eid"],
    embroideryType: "None",
    embellishmentType: "Metallic foil floral accents, matching chiffon scarf",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/metallic-floral-sage-abaya-set/1.jpg", "Metallic Floral Sage Abaya Set, front view", "portrait")],
    relatedProductIds: ["p-mocha-marble", "p-cotton-prayer-dress"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Size M, approx. length 140-142cm — to be confirmed with supplier.",
    constructionDetails: ["Metallic foil floral print", "Matching plain chiffon scarf", "Refined, balanced silhouette"],
    accuracyTag: "representative",
  },
  {
    id: "p-cotton-prayer-dress",
    slug: "cotton-prayer-dress",
    name: "Cotton Prayer Dress",
    collectionSlug: "signature-abayas",
    description: "Soft, breathable cotton prayer dress with a delicate micro-floral print and elasticated cuffs.",
    editorialDescription:
      "(Different colors available) Soft, breathable premium cotton prayer dress with a delicate micro-floral print, elasticated cuffs, and a matching attached headscarf.",
    price: 39,
    currency: "AED",
    colours: [variant("mustard-floral", "Mustard Micro-Floral", "#d4c078", "plain-unembroidered")],
    sizes: SIZES,
    lengths: LENGTHS,
    fabricId: "plain-unembroidered",
    cut: "Relaxed",
    sleeve: "Elasticated cuff",
    occasion: ["Everyday", "Ramadan"],
    embroideryType: "None",
    embellishmentType: "Micro-floral print, attached headscarf",
    care: CARE_STANDARD,
    availability: "in-stock",
    images: [img("/images/products/cotton-prayer-dress/1.jpg", "Cotton Prayer Dress, front view", "portrait")],
    relatedProductIds: ["p-monochrome-polka-dot", "p-metallic-floral-sage"],
    modelMeasurements: "Measurements to be confirmed with supplier.",
    productMeasurements: "Free size — to be confirmed with supplier.",
    constructionDetails: ["Attached matching headscarf", "Elasticated cuffs", "Breathable cotton", "Micro-floral print"],
    accuracyTag: "representative",
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCollection(collectionSlug: string) {
  return products.filter((p) => p.collectionSlug === collectionSlug);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.isFeatured);
}

export function getRelatedProducts(product: Product) {
  return product.relatedProductIds
    .map((id) => products.find((p) => p.id === id))
    .filter((p): p is Product => Boolean(p));
}
